//! Autogenerated weights for pallet_template
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-03-31
//! STEPS: `50`, REPEAT: `20`
//!
//! **NOTE**: These weights are placeholder estimates. Run benchmarks on your own hardware for
//! accurate production values:
//!
//! ```sh
//! cargo build --release --features runtime-benchmarks
//! ./target/release/polkadot-omni-node benchmark pallet \
//!     --chain dev \
//!     --pallet pallet_template \
//!     --extrinsic '*' \
//!     --steps 50 \
//!     --repeat 20 \
//!     --output pallets/template/src/weights.rs
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_template.
pub trait WeightInfo {
	fn create_claim() -> Weight;
	fn revoke_claim() -> Weight;
}

/// Weights for pallet_template using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TemplatePallet::Claims` (r:1 w:1)
	fn create_claim() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: `TemplatePallet::Claims` (r:1 w:1)
	fn revoke_claim() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

/// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_claim() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn revoke_claim() -> Weight {
		Weight::from_parts(11_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
