use clap::{Parser, Subcommand};
use std::path::PathBuf;

/// Trusted off-chain wrapper/granter for ppview listings.
///
/// See `docs/design/spec.md` §5 ("Chain-service grant flow") for the end-to-end
/// flow this daemon implements.
#[derive(Debug, Parser)]
#[command(name = "ppview-chain-service", version)]
pub struct Args {
    /// Parachain RPC endpoint (websocket).
    #[arg(long, env = "PPVIEW_RPC_URL", default_value = "ws://127.0.0.1:9944")]
    pub rpc_url: String,

    /// Path to the PKCS#8 PEM file holding SVC_PRIV (x25519 secret).
    /// Generated by `scripts/gen-service-key.sh`.
    #[arg(long, env = "PPVIEW_SVC_PRIV", default_value = "keys/svc_priv.pem")]
    pub svc_priv_path: PathBuf,

    /// Path to the sr25519 service-signer SURI file. Must resolve to the
    /// AccountId baked into `ServiceAccountId` at genesis. Generated by
    /// `scripts/gen-service-key.sh`.
    #[arg(long, env = "PPVIEW_SERVICE_SIGNER", default_value = "keys/svc_signer.suri")]
    pub service_signer_path: PathBuf,

    /// Inline SURI override (e.g. `//Dave`). When set, bypasses
    /// `--service-signer-path`. Intended for ad-hoc dev use; keep secrets in
    /// the file for anything production-shaped.
    #[arg(long, env = "PPVIEW_SERVICE_SURI")]
    pub service_suri: Option<String>,

    /// Tracing filter (e.g. `info`, `ppview_chain_service=debug`).
    #[arg(long, env = "PPVIEW_LOG", default_value = "info")]
    pub log: String,

    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Load the configured service signer and print its AccountId in both
    /// SS58 and raw 32-byte hex form (plus a paste-ready Rust literal for
    /// the runtime's `SERVICE_ACCOUNT_ID` constant).
    PrintServiceAccount,
}
