use clap::Parser;
use std::path::PathBuf;

/// Trusted off-chain wrapper/granter for ppview listings.
///
/// See `docs/design/spec.md` §5 ("Chain-service grant flow") for the end-to-end
/// flow this daemon implements.
#[derive(Debug, Parser)]
#[command(name = "ppview-chain-service", version)]
pub struct Args {
    /// Parachain RPC endpoint (websocket).
    #[arg(long, env = "PPVIEW_RPC_URL", default_value = "ws://127.0.0.1:9944")]
    pub rpc_url: String,

    /// Path to the PKCS#8 PEM file holding SVC_PRIV (x25519 secret).
    /// Generated by `scripts/gen-service-key.sh`.
    #[arg(long, env = "PPVIEW_SVC_PRIV", default_value = "keys/svc_priv.pem")]
    pub svc_priv_path: PathBuf,

    /// SURI for the sr25519 service-account signer. Must match the AccountId
    /// stored in `ServiceAccountId` at genesis (default is `//Dave` for local dev).
    #[arg(long, env = "PPVIEW_SERVICE_SURI", default_value = "//Dave")]
    pub service_suri: String,

    /// Tracing filter (e.g. `info`, `ppview_chain_service=debug`).
    #[arg(long, env = "PPVIEW_LOG", default_value = "info")]
    pub log: String,
}
